# Generated by Django 5.0.4 on 2024-05-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenDV', models.CharField(max_length=100)),
                ('gia', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('soHD', models.AutoField(primary_key=True, serialize=False)),
                ('ngayTao', models.DateField()),
                ('t_start', models.TimeField()),
                ('t_end', models.TimeField()),
                ('tongTien', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('hoTen', models.CharField(max_length=50)),
                ('SDT', models.CharField(max_length=12)),
                ('diaChi', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenLoai', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoTen', models.CharField(max_length=50)),
                ('SDT', models.CharField(max_length=12)),
                ('diaChi', models.CharField(max_length=100)),
                ('gioiTinh', models.CharField(max_length=5)),
                ('ngaySinh', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoanAdmin',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.CharField(max_length=10)),
                ('dv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NguoiDung.dichvu')),
                ('soHD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NguoiDung.hoadon')),
            ],
        ),
        migrations.AddField(
            model_name='hoadon',
            name='kh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NguoiDung.khachhang'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='nv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NguoiDung.nhanvien'),
        ),
        migrations.CreateModel(
            name='SanBong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenSan', models.CharField(max_length=100)),
                ('tinhTrang', models.CharField(max_length=100)),
                ('kichThuoc', models.CharField(max_length=6)),
                ('maloai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NguoiDung.loaisan')),
            ],
        ),
        migrations.CreateModel(
            name='DatSan',
            fields=[
                ('maLichDat', models.AutoField(primary_key=True, serialize=False)),
                ('thoiGianDat', models.DateTimeField()),
                ('kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NguoiDung.khachhang')),
                ('san', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NguoiDung.sanbong')),
            ],
        ),
    ]
